export const CREATE_PUBLICATION = "CREATE_PUBLICATION";
export const CREATE_PUBLICATION_SUCCESS = "CREATE_PUBLICATION_SUCCESS";
export const CREATE_PUBLICATION_FAIL = "CREATE_PUBLICATION_FAIL";

export const DELETE_PUBLICATION = "DELETE_PUBLICATION";
export const DELETE_PUBLICATION_SUCCESS = "DELETE_PUBLICATION_SUCCESS";
export const DELETE_PUBLICATION_FAIL = "DELETE_PUBLICATION_FAIL";

export const PUT_PUBLICATION = "PUT_PUBLICATION";
export const PUT_PUBLICATION_SUCCESS = "PUT_PUBLICATION_SUCCESS";
export const PUT_PUBLICATION_FAIL = "PUT_PUBLICATION_FAIL";

export const GET_PUBLICATION = "GET_PUBLICATION";
export const GET_PUBLICATION_SUCCESS = "GET_PUBLICATION_SUCCESS";
export const GET_PUBLICATION_FAIL = "GET_PUBLICATION_FAIL";
